DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS solutions;

CREATE TABLE tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sender TEXT NOT NULL,
    text TEXT NOT NULL,
    status INTEGER NOT NULL
);

CREATE TABLE solutions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id INTEGER UNIQUE NOT NULL,
    text TEXT NOT NULL
);